
Skip to content
Pull requests
Issues
Codespaces
Marketplace
Explore
@Plat0nicS0lid
Plat0nicS0lid /
gitops-cert-level-2-examples
Public
forked from codefresh-contrib/gitops-cert-level-2-examples

Code
Pull requests
Actions
Projects
Wiki
Security
Insights

    Settings

gitops-cert-level-2-examples/app-of-apps/more-apps/argo-workflows.yml
@kostis-codefresh
kostis-codefresh Added more apps
Latest commit d443677 Jul 28, 2022
History
1 contributor
32 lines (28 sloc) 1.24 KB
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    repoURL: https://github.com/codefresh-contrib/gitops-cert-level-2-examples.git
    targetRevision: HEAD
    path: ./app-of-apps/manifests
   
  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-workflows

  # Sync policy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
  
Footer
© 2022 GitHub, Inc.
Footer navigation

    Terms
    Privacy
    Security
    Status
    Docs
    Contact GitHub
    Pricing
    API
    Training
    Blog
    About

gitops-cert-level-2-examples/argo-workflows.yml at main · Plat0nicS0lid/gitops-cert-level-2-examples
